import { Injectable, signal } from '@angular/core';

export type SiteLanguage = 'hinglish' | 'hi' | 'en';

const translations: Record<SiteLanguage, Record<string, string>> = {
  hinglish: {
    home: 'Home', sites: 'Sites', allSites: 'All Sites', pricingEmi: 'Pricing & EMI',
    buyback: 'Buyback', earnWithUs: 'Earn With Us', contact: 'Contact', login: 'Login',
    register: 'Register', ourSites: 'Our Sites', facilities: 'Facilities', contactUs: 'Contact Us',
    loadingSites: 'Loading sites...', noSites: 'No sites available', language: 'Language',
    govtRegistered: 'Trust of 20 years', bankFinance: 'Bank Finance', buybackGuarantee: 'Trusted Partner',
    androidApp: 'Android App', pdfVouchers: 'PDF Vouchers', whyMmr: 'Why MMR',
    whyChoose: 'Why Choose M.M.R.?', infrastructure: 'Infrastructure',
    worldFacilities: 'World-Class Facilities', limitedAvailability: 'Limited Availability',
    registerNow: 'Abhi Register karein,', lockPlot: 'Plot Lock karein',
    limitedPlots: 'Plots ki limited availability hai. Registration free hai.',
    registerFree: 'Register Free', callNow: 'Call Now',
    plotBooking: 'Plot Booking', availability: 'Availability',
    siteIntro: 'Live plot counts dekhein aur har project ka interactive booking map open karein.',
    vacant: 'Vacant', inProcess: 'In Process', booked: 'Booked', totalPlots: 'Total Plots',
    viewPlots: 'View Plots', noActiveSites: 'Abhi koi active site available nahi hai.',
    bookSiteVisit: 'Schedule a Site Visit', visitDesc: 'Personal visit schedule karein aur hamari team ke saath plots review karein.',
    bookVisit: 'Book Visit', seeAllSites: 'See All Sites', showLessSites: 'Show Less Sites',
    unsold: 'Unsold', sold: 'Sold', mapSoon: 'Plot map jaldi available hoga.',
    transparentPricing: 'Transparent Pricing', emiCalculator: 'EMI Calculator',
    emiIntro: 'Plot size choose karein aur database se live EMI breakdown dekhein.',
    databasePlans: 'Database-driven plans', adminUpdate: 'Admin kabhi bhi update kar sakta hai',
    autoCalculated: 'Loan aur EMI auto calculated', noHidden: 'Frontend mein koi hidden values nahi',
    selectPlotSize: 'Select Plot Size', noEmiPlans: 'Koi active EMI plan available nahi hai.',
    downPayment: 'Down Payment', monthlyEmi: 'Monthly EMI', plotPrice: 'Plot Price',
    tenure: 'Tenure', months: 'months', processingFee: 'Processing Fee', loanAmount: 'Loan Amount',
    interest: 'Interest', totalPayable: 'Total Payable', bookPlotNow: 'Book a Plot Now',
    associateProgram: 'Associate Program', earnCommission: 'Earn Commission', for12Years: 'For 12 Years',
    earnIntro: 'Plot bechein, commission paayen — aur woh bhi 12 saal tak har mahine.',
    howItWorks: 'How It Works', becomeAssociate: 'Become an Associate — Free',
    riskFree: 'Risk-Free Investment', ourBuyback: 'Our Buyback Guarantee',
    buybackIntro: 'India ki un chuninda real estate companies mein se ek jo genuine buyback guarantee deti hai.',
    readPolicy: 'Read Full Policy', getInTouch: 'Get In Touch', contactHeading: 'Contact Us',
    contactIntro: 'Koi question, site visit ya enquiry ho to humse contact karein.',
    phone: 'Phone', office: 'Office', registration: 'Registration', sendEnquiry: 'Send Enquiry',
    sending: 'Sending...', thankYou: "Thank you! Hum aapse jaldi contact karenge.",
    yourName: 'Your Name *', fullName: 'Full Name', mobileNumber: 'Mobile Number *',
    mobilePlaceholder: '10-digit mobile', emailAddress: 'Email Address', emailPlaceholder: 'Email address',
    interestedIn: 'Interested In', message: 'Message', messagePlaceholder: 'Your message...',
    quickLinks: 'Quick Links', account: 'Account', customerLogin: 'Customer Login',
    joinAssociate: 'Join as Associate', termsConditions: 'Terms & Conditions', privacyPolicy: 'Privacy Policy',
    footerDesc: 'Kanpur, Unnao aur Lucknow mein premium affordable plots — buyback guarantee aur 12-year commission program ke saath.',
    whyBuybackTitle: 'Trust of 20 years', whyBuybackDesc: '20 years ka trusted real-estate experience aur customer-first service.',
    whyEmiTitle: 'Easy EMI', whyEmiDesc: '₹51,000 down payment se shuru. ₹3,000/month EMI aur bank finance available.',
    whyLocationTitle: 'Prime Locations', whyLocationDesc: 'Highway, airport aur station ke nazdeek high-appreciation plots.',
    whyRegisteredTitle: 'Trusted Partner', whyRegisteredDesc: 'Har step par transparent guidance aur reliable customer support.',
    roadTitle: 'Paved Roads', roadDesc: 'Sabhi sites par internal paved road network.',
    drainageTitle: 'Drainage', drainageDesc: 'Complete paved drainage system.',
    electricityTitle: '24×7 Electricity', electricityDesc: 'Uninterrupted power supply.',
    financeTitle: 'Bank Finance', financeDesc: 'Bank loan facility available.',
    appTitle: 'Android App', appDesc: 'Plot tracking, EMI aur payments.',
    voucherTitle: 'PDF Vouchers', voucherDesc: 'Har payment par downloadable receipt.',
  },
  hi: {
    home: 'होम', sites: 'साइटें', allSites: 'सभी साइटें', pricingEmi: 'मूल्य और ईएमआई',
    buyback: 'बायबैक', earnWithUs: 'हमारे साथ कमाएँ', contact: 'संपर्क', login: 'लॉगिन',
    register: 'पंजीकरण', ourSites: 'हमारी साइटें', facilities: 'सुविधाएँ', contactUs: 'संपर्क करें',
    loadingSites: 'साइटें लोड हो रही हैं...', noSites: 'कोई साइट उपलब्ध नहीं है', language: 'भाषा',
    govtRegistered: 'Trust of 20 years', bankFinance: 'बैंक वित्त', buybackGuarantee: 'Trusted Partner',
    androidApp: 'एंड्रॉयड ऐप', pdfVouchers: 'पीडीएफ वाउचर', whyMmr: 'एम.एम.आर. क्यों',
    whyChoose: 'एम.एम.आर. को क्यों चुनें?', infrastructure: 'आधारभूत संरचना',
    worldFacilities: 'विश्वस्तरीय सुविधाएँ', limitedAvailability: 'सीमित उपलब्धता',
    registerNow: 'अभी पंजीकरण करें,', lockPlot: 'अपना प्लॉट सुरक्षित करें',
    limitedPlots: 'प्लॉट सीमित संख्या में उपलब्ध हैं। पंजीकरण निःशुल्क है।',
    registerFree: 'निःशुल्क पंजीकरण', callNow: 'अभी कॉल करें',
    plotBooking: 'प्लॉट बुकिंग', availability: 'उपलब्धता',
    siteIntro: 'लाइव प्लॉट संख्या देखें और प्रत्येक परियोजना का इंटरैक्टिव बुकिंग मानचित्र खोलें।',
    vacant: 'खाली', inProcess: 'प्रक्रिया में', booked: 'बुक किया गया', totalPlots: 'कुल प्लॉट',
    viewPlots: 'प्लॉट देखें', noActiveSites: 'अभी कोई सक्रिय साइट उपलब्ध नहीं है।',
    bookSiteVisit: 'साइट विजिट बुक करें', visitDesc: 'व्यक्तिगत विजिट तय करें और हमारी टीम के साथ प्लॉट देखें।',
    bookVisit: 'विजिट बुक करें', seeAllSites: 'सभी साइटें देखें', showLessSites: 'कम साइटें दिखाएँ',
    unsold: 'बिना बिका', sold: 'बिका हुआ', mapSoon: 'प्लॉट मानचित्र जल्द उपलब्ध होगा।',
    transparentPricing: 'पारदर्शी मूल्य', emiCalculator: 'ईएमआई कैलकुलेटर',
    emiIntro: 'प्लॉट का आकार चुनें और लाइव ईएमआई विवरण देखें।',
    databasePlans: 'डेटाबेस आधारित योजनाएँ', adminUpdate: 'एडमिन कभी भी अपडेट कर सकता है',
    autoCalculated: 'ऋण और ईएमआई की स्वतः गणना', noHidden: 'कोई छिपा हुआ मूल्य नहीं',
    selectPlotSize: 'प्लॉट का आकार चुनें', noEmiPlans: 'कोई सक्रिय ईएमआई योजना उपलब्ध नहीं है।',
    downPayment: 'अग्रिम भुगतान', monthlyEmi: 'मासिक ईएमआई', plotPrice: 'प्लॉट मूल्य',
    tenure: 'अवधि', months: 'महीने', processingFee: 'प्रोसेसिंग शुल्क', loanAmount: 'ऋण राशि',
    interest: 'ब्याज', totalPayable: 'कुल देय', bookPlotNow: 'अभी प्लॉट बुक करें',
    associateProgram: 'एसोसिएट कार्यक्रम', earnCommission: 'कमीशन कमाएँ', for12Years: '12 वर्षों तक',
    earnIntro: 'प्लॉट बेचें और 12 वर्षों तक हर महीने कमीशन पाएँ।',
    howItWorks: 'यह कैसे काम करता है', becomeAssociate: 'निःशुल्क एसोसिएट बनें',
    riskFree: 'जोखिम-मुक्त निवेश', ourBuyback: 'हमारी बायबैक गारंटी',
    buybackIntro: 'भारत की चुनिंदा रियल एस्टेट कंपनियों में से एक, जो वास्तविक बायबैक गारंटी देती है।',
    readPolicy: 'पूरी नीति पढ़ें', getInTouch: 'संपर्क में रहें', contactHeading: 'हमसे संपर्क करें',
    contactIntro: 'किसी प्रश्न, साइट विजिट या पूछताछ के लिए हमसे संपर्क करें।',
    phone: 'फोन', office: 'कार्यालय', registration: 'पंजीकरण', sendEnquiry: 'पूछताछ भेजें',
    sending: 'भेजा जा रहा है...', thankYou: 'धन्यवाद! हम जल्द ही आपसे संपर्क करेंगे।',
    yourName: 'आपका नाम *', fullName: 'पूरा नाम', mobileNumber: 'मोबाइल नंबर *',
    mobilePlaceholder: '10 अंकों का मोबाइल नंबर', emailAddress: 'ईमेल पता', emailPlaceholder: 'ईमेल पता',
    interestedIn: 'रुचि का विषय', message: 'संदेश', messagePlaceholder: 'अपना संदेश लिखें...',
    quickLinks: 'त्वरित लिंक', account: 'खाता', customerLogin: 'ग्राहक लॉगिन',
    joinAssociate: 'एसोसिएट के रूप में जुड़ें', termsConditions: 'नियम और शर्तें', privacyPolicy: 'गोपनीयता नीति',
    footerDesc: 'कानपुर, उन्नाव और लखनऊ में प्रीमियम किफायती प्लॉट — बायबैक गारंटी और 12-वर्षीय कमीशन कार्यक्रम के साथ।',
    whyBuybackTitle: 'Trust of 20 years', whyBuybackDesc: '20 वर्षों का भरोसेमंद रियल-एस्टेट अनुभव और ग्राहक-प्रथम सेवा।',
    whyEmiTitle: 'आसान ईएमआई', whyEmiDesc: '₹51,000 अग्रिम भुगतान से शुरुआत। ₹3,000 मासिक ईएमआई और बैंक वित्त उपलब्ध।',
    whyLocationTitle: 'प्रमुख स्थान', whyLocationDesc: 'राजमार्ग, हवाई अड्डे और स्टेशन के पास उच्च मूल्यवृद्धि वाले प्लॉट।',
    whyRegisteredTitle: 'Trusted Partner', whyRegisteredDesc: 'हर कदम पर पारदर्शी मार्गदर्शन और भरोसेमंद ग्राहक सहायता।',
    roadTitle: 'पक्की सड़कें', roadDesc: 'सभी साइटों पर आंतरिक पक्की सड़कें।',
    drainageTitle: 'जल निकासी', drainageDesc: 'संपूर्ण पक्की जल निकासी व्यवस्था।',
    electricityTitle: '24×7 बिजली', electricityDesc: 'निर्बाध बिजली आपूर्ति।',
    financeTitle: 'बैंक वित्त', financeDesc: 'बैंक ऋण सुविधा उपलब्ध।',
    appTitle: 'एंड्रॉयड ऐप', appDesc: 'प्लॉट, ईएमआई और भुगतान की जानकारी।',
    voucherTitle: 'पीडीएफ वाउचर', voucherDesc: 'हर भुगतान पर डाउनलोड योग्य रसीद।',
  },
  en: {
    home: 'Home', sites: 'Sites', allSites: 'All Sites', pricingEmi: 'Pricing & EMI',
    buyback: 'Buyback', earnWithUs: 'Earn With Us', contact: 'Contact', login: 'Login',
    register: 'Register', ourSites: 'Our Sites', facilities: 'Facilities', contactUs: 'Contact Us',
    loadingSites: 'Loading sites...', noSites: 'No sites available', language: 'Language',
    govtRegistered: 'Trust of 20 years', bankFinance: 'Bank Finance', buybackGuarantee: 'Trusted Partner',
    androidApp: 'Android App', pdfVouchers: 'PDF Vouchers', whyMmr: 'Why MMR',
    whyChoose: 'Why Choose M.M.R.?', infrastructure: 'Infrastructure',
    worldFacilities: 'World-Class Facilities', limitedAvailability: 'Limited Availability',
    registerNow: 'Register Now,', lockPlot: 'Secure Your Plot',
    limitedPlots: 'Plots are available in limited numbers. Registration is free.',
    registerFree: 'Register Free', callNow: 'Call Now',
    plotBooking: 'Plot Booking', availability: 'Availability',
    siteIntro: 'Browse live plot counts and open the interactive booking map for each project.',
    vacant: 'Vacant', inProcess: 'In Process', booked: 'Booked', totalPlots: 'Total Plots',
    viewPlots: 'View Plots', noActiveSites: 'No active sites are available right now.',
    bookSiteVisit: 'Schedule a Site Visit', visitDesc: 'Schedule a personal visit and review plots with our team.',
    bookVisit: 'Book Visit', seeAllSites: 'See All Sites', showLessSites: 'Show Fewer Sites',
    unsold: 'Unsold', sold: 'Sold', mapSoon: 'The plot map will be available soon.',
    transparentPricing: 'Transparent Pricing', emiCalculator: 'EMI Calculator',
    emiIntro: 'Choose a plot size and view the live EMI breakdown from the database.',
    databasePlans: 'Database-driven plans', adminUpdate: 'Admin can update at any time',
    autoCalculated: 'Loan and EMI calculated automatically', noHidden: 'No hidden frontend values',
    selectPlotSize: 'Select Plot Size', noEmiPlans: 'No active EMI plans are available.',
    downPayment: 'Down Payment', monthlyEmi: 'Monthly EMI', plotPrice: 'Plot Price',
    tenure: 'Tenure', months: 'months', processingFee: 'Processing Fee', loanAmount: 'Loan Amount',
    interest: 'Interest', totalPayable: 'Total Payable', bookPlotNow: 'Book a Plot Now',
    associateProgram: 'Associate Program', earnCommission: 'Earn Commission', for12Years: 'For 12 Years',
    earnIntro: 'Sell plots and receive a monthly commission for 12 years.',
    howItWorks: 'How It Works', becomeAssociate: 'Become an Associate — Free',
    riskFree: 'Risk-Free Investment', ourBuyback: 'Our Buyback Guarantee',
    buybackIntro: 'One of the select real estate companies in India offering a genuine buyback guarantee.',
    readPolicy: 'Read Full Policy', getInTouch: 'Get In Touch', contactHeading: 'Contact Us',
    contactIntro: 'Contact us with any question, site visit request, or enquiry.',
    phone: 'Phone', office: 'Office', registration: 'Registration', sendEnquiry: 'Send Enquiry',
    sending: 'Sending...', thankYou: "Thank you! We'll contact you shortly.",
    yourName: 'Your Name *', fullName: 'Full Name', mobileNumber: 'Mobile Number *',
    mobilePlaceholder: '10-digit mobile', emailAddress: 'Email Address', emailPlaceholder: 'Email address',
    interestedIn: 'Interested In', message: 'Message', messagePlaceholder: 'Your message...',
    quickLinks: 'Quick Links', account: 'Account', customerLogin: 'Customer Login',
    joinAssociate: 'Join as Associate', termsConditions: 'Terms & Conditions', privacyPolicy: 'Privacy Policy',
    footerDesc: 'Premium affordable plots in Kanpur, Unnao, and Lucknow with a buyback guarantee and a 12-year commission program.',
    whyBuybackTitle: 'Trust of 20 years', whyBuybackDesc: '20 years of trusted real-estate experience with customer-first service.',
    whyEmiTitle: 'Easy EMI', whyEmiDesc: 'Start with a ₹51,000 down payment, EMI from ₹3,000 per month, and available bank finance.',
    whyLocationTitle: 'Prime Locations', whyLocationDesc: 'High-appreciation plots near highways, airports, and railway stations.',
    whyRegisteredTitle: 'Trusted Partner', whyRegisteredDesc: 'Transparent guidance and reliable customer support at every step.',
    roadTitle: 'Paved Roads', roadDesc: 'Internal paved road networks across all sites.',
    drainageTitle: 'Drainage', drainageDesc: 'A complete paved drainage system.',
    electricityTitle: '24×7 Electricity', electricityDesc: 'Uninterrupted power supply.',
    financeTitle: 'Bank Finance', financeDesc: 'Bank loan facilities are available.',
    appTitle: 'Android App', appDesc: 'Track plots, EMI, and payments.',
    voucherTitle: 'PDF Vouchers', voucherDesc: 'Downloadable receipts for every payment.',
  },
};

const sectionTranslations: Record<SiteLanguage, Record<string, string>> = {
  hinglish: {
    blog: 'Blog', blogs: 'Blogs', policies: 'Policies', companyDocuments: 'Company Documents',
    backToHome: 'Back to Home', backToBlogs: 'Back to Blogs', readMore: 'Read More',
    readArticle: 'Read article', continueReading: 'Continue reading', relatedBlogs: 'Related Blogs',
    by: 'By', propertyKnowledge: 'Property knowledge', officialWebsitePolicy: 'Official Website Policy',
    effectiveDate: 'Effective date', policyBookingNote: 'For a specific property booking, the signed agreement and transaction documents take precedence over general website information.',
    transparencyTrust: 'Transparency & Trust', companyVerificationDocuments: 'Company Verification Documents',
    companyRecords: 'Company Records', officialBusinessDocuments: 'Official business documents',
    publicVerification: 'Public Verification', viewPublishedRecords: 'View active published records',
    secureStorage: 'Secure Storage', managedAdminPanel: 'Managed through Admin Panel',
    loadingDocuments: 'Loading verification documents...', noDocuments: 'No documents published yet',
    noDocumentsDesc: 'Active company documents will appear here after verification and publication by the administrator.',
    pdfDocument: 'PDF Document', certificate: 'Certificate', officialVerificationDocument: 'Official company verification document.',
    viewPdf: 'View PDF', viewDocument: 'View Document', download: 'Download',
    documentsVerificationNote: 'These copies are provided for convenient public verification. For transaction-specific due diligence, request the relevant original or certified documents from the company office.',
    blogIntro: 'MMR Constructions shares practical guidance to help customers explore genuine, affordable and suitable property options in Unnao and nearby cities with greater confidence.',
    blogNotFound: 'Blog not found', blogNotFoundDesc: 'The article you are looking for may have been moved or is no longer available.',
    documentsLoadError: 'Company documents could not be loaded.',
  },
  hi: {
    blog: 'ब्लॉग', blogs: 'ब्लॉग', policies: 'नीतियाँ', companyDocuments: 'कंपनी दस्तावेज़',
    backToHome: 'होम पर वापस जाएँ', backToBlogs: 'ब्लॉग पर वापस जाएँ', readMore: 'और पढ़ें',
    readArticle: 'लेख पढ़ें', continueReading: 'आगे पढ़ें', relatedBlogs: 'संबंधित ब्लॉग',
    by: 'लेखक', propertyKnowledge: 'संपत्ति संबंधी जानकारी', officialWebsitePolicy: 'आधिकारिक वेबसाइट नीति',
    effectiveDate: 'प्रभावी तिथि', policyBookingNote: 'किसी विशेष संपत्ति बुकिंग के लिए हस्ताक्षरित समझौते और लेन-देन के दस्तावेज़ सामान्य वेबसाइट जानकारी से अधिक प्रभावी होंगे।',
    transparencyTrust: 'पारदर्शिता और विश्वास', companyVerificationDocuments: 'कंपनी सत्यापन दस्तावेज़',
    companyRecords: 'कंपनी रिकॉर्ड', officialBusinessDocuments: 'आधिकारिक व्यावसायिक दस्तावेज़',
    publicVerification: 'सार्वजनिक सत्यापन', viewPublishedRecords: 'प्रकाशित सक्रिय रिकॉर्ड देखें',
    secureStorage: 'सुरक्षित संग्रहण', managedAdminPanel: 'एडमिन पैनल द्वारा प्रबंधित',
    loadingDocuments: 'सत्यापन दस्तावेज़ लोड हो रहे हैं...', noDocuments: 'अभी कोई दस्तावेज़ प्रकाशित नहीं है',
    noDocumentsDesc: 'सत्यापन और एडमिन द्वारा प्रकाशन के बाद सक्रिय कंपनी दस्तावेज़ यहाँ दिखाई देंगे।',
    pdfDocument: 'पीडीएफ दस्तावेज़', certificate: 'प्रमाणपत्र', officialVerificationDocument: 'आधिकारिक कंपनी सत्यापन दस्तावेज़।',
    viewPdf: 'पीडीएफ देखें', viewDocument: 'दस्तावेज़ देखें', download: 'डाउनलोड',
    documentsVerificationNote: 'ये प्रतियाँ सुविधाजनक सार्वजनिक सत्यापन के लिए दी गई हैं। किसी विशेष लेन-देन की जाँच के लिए कंपनी कार्यालय से संबंधित मूल या प्रमाणित दस्तावेज़ माँगें।',
    blogIntro: 'MMR Constructions ग्राहकों को उन्नाव और आसपास के शहरों में वास्तविक, किफायती और उपयुक्त संपत्ति विकल्प अधिक विश्वास के साथ खोजने के लिए व्यावहारिक मार्गदर्शन देता है।',
    blogNotFound: 'ब्लॉग नहीं मिला', blogNotFoundDesc: 'आप जिस लेख को खोज रहे हैं, उसे स्थानांतरित किया गया हो सकता है या वह अब उपलब्ध नहीं है।',
    documentsLoadError: 'कंपनी दस्तावेज़ लोड नहीं किए जा सके।',
  },
  en: {
    blog: 'Blog', blogs: 'Blogs', policies: 'Policies', companyDocuments: 'Company Documents',
    backToHome: 'Back to Home', backToBlogs: 'Back to Blogs', readMore: 'Read More',
    readArticle: 'Read article', continueReading: 'Continue reading', relatedBlogs: 'Related Blogs',
    by: 'By', propertyKnowledge: 'Property knowledge', officialWebsitePolicy: 'Official Website Policy',
    effectiveDate: 'Effective date', policyBookingNote: 'For a specific property booking, the signed agreement and transaction documents take precedence over general website information.',
    transparencyTrust: 'Transparency & Trust', companyVerificationDocuments: 'Company Verification Documents',
    companyRecords: 'Company Records', officialBusinessDocuments: 'Official business documents',
    publicVerification: 'Public Verification', viewPublishedRecords: 'View active published records',
    secureStorage: 'Secure Storage', managedAdminPanel: 'Managed through Admin Panel',
    loadingDocuments: 'Loading verification documents...', noDocuments: 'No documents published yet',
    noDocumentsDesc: 'Active company documents will appear here after verification and publication by the administrator.',
    pdfDocument: 'PDF Document', certificate: 'Certificate', officialVerificationDocument: 'Official company verification document.',
    viewPdf: 'View PDF', viewDocument: 'View Document', download: 'Download',
    documentsVerificationNote: 'These copies are provided for convenient public verification. For transaction-specific due diligence, request the relevant original or certified documents from the company office.',
    blogIntro: 'MMR Constructions shares practical guidance to help customers explore genuine, affordable and suitable property options in Unnao and nearby cities with greater confidence.',
    blogNotFound: 'Blog not found', blogNotFoundDesc: 'The article you are looking for may have been moved or is no longer available.',
    documentsLoadError: 'Company documents could not be loaded.',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly current = signal<SiteLanguage>(this.savedLanguage());

  constructor() {
    this.applyDocumentLanguage(this.current());
  }

  setLanguage(language: SiteLanguage) {
    this.current.set(language);
    localStorage.setItem('mmr_site_language', language);
    this.applyDocumentLanguage(language);
  }

  translate(key: string): string {
    return sectionTranslations[this.current()][key]
      || translations[this.current()][key]
      || sectionTranslations.hinglish[key]
      || translations.hinglish[key]
      || key;
  }

  private savedLanguage(): SiteLanguage {
    const saved = localStorage.getItem('mmr_site_language');
    return saved === 'hi' || saved === 'en' || saved === 'hinglish' ? saved : 'hinglish';
  }

  private applyDocumentLanguage(language: SiteLanguage) {
    document.documentElement.lang = language === 'hi' ? 'hi' : 'en-IN';
  }
}
